### ISSUE TITLE
CookieJar.setCookieSync returns a cookie

### ISSUE THREAD

**Issue by demurgos** [types/npm-tough-cookie#1]
Hi,
It's not obvious from `tough-cookie`'s documentation, but when you [look at the test](https://github.com/SalesforceEng/tough-cookie/blob/cc46628c4d7d2e8c372ecba29293ca8a207ec192/test/api_test.js#L243), `CookieJar.setCookieSync` returns a `Cookie`.
(currently it is defined as `void`)

**Comment by blakeembrey** [comment]
Makes sense, I'll correct thanks, cheers!

**Comment by blakeembrey** [comment]
Fixed with https://github.com/typed-typings/npm-tough-cookie/commit/fb187275eb7ac993af03b6802cd2958ac66b0828 and updated in the registry: https://github.com/typings/registry/pull/377.

**Comment by demurgos** [comment]
Thank you.
I did not check every other method, but if I spot an issue I'll let you know.
(This one was related to the [update of the request's typings](https://github.com/typings/registry/pull/374), it's the only method used by `request`).

**Comment by blakeembrey** [comment]
Awesome, cheers! I remember spending a _long_ time typings this module, so I'm sure there won't be many bugs - seems like that one was a bad copy from the async method.
